name: Docker Build (Debian)

on:
  push:
    paths:
      - "Dockerfile.debian"

env:
  DOCKER_REPOSITORY: abcfy2/zhparser

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_tag:
          - latest
          - 9.6
          - 10
          - 11
          - 12
          - 13
          - 14
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.debian
          build-args: |
            PG_TAG=${{ matrix.pg_tag }}
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ matrix.pg_tag }}
