name: Docker Build (Alpine)

on:
  push:
    paths:
      - "Dockerfile.alpine"

env:
  DOCKER_REPOSITORY: abcfy2/zhparser

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_tag:
          - alpine
          - 9.6-alpine
          - 10-alpine
          - 11-alpine
          - 12-alpine
          - 13-alpine
          - 14-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.alpine
          build-args: |
            PG_TAG=${{ matrix.pg_tag }}
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ matrix.pg_tag }}
